#!/bin/bash
set -e

docker buildx build --platform linux/amd64 -t linux_env .
if [ -e /usr/local/bin/ubuntu ]; then
    sudo rm -rf /usr/local/bin/ubuntu
fi
sudo ln -s $PWD/run /usr/local/bin/ubuntu 

