#!/bin/bash
echo "Change github info in Dockerfile otherwise it says I authored everything lmao"
read -n 1 -s -r -p "Press any key to continue if you read above..."
docker build -t java_linux_env .
echo "Installing \"jubuntu\" to /usr/local/bin..."
sudo cp run /usr/local/bin/jubuntu
echo "Done! To use the ubuntu docker env just type "jubuntu" in terminal wherever you want to mount your folder!"
